package ca.gbc.comp3095.inventoryservice.repository;

import ca.gbc.comp3095.inventoryservice.model.Inventory;
import org.springframework.data.jpa.repository.JpaRepository;

public interface InventoryRepository extends JpaRepository<Inventory,Long> {


    /**
     * Custom query method generated by Spring Data JPA, Based on method name, Spring Data JPA
     * automatically dervies the appropriate SQL query to check if the inventory item with the
     * given SKU_CODE exists and whether its quantity is greater than or equal to the specified amount.
     * @param skuCode the SKU Code of the inventory
     * @param quantity the minim quantity required
     * @return true if an item of the given skucode exists and its quantity is greater than or equal to the given value
     */
    boolean existsBySkuCodeAndQuantityGreaterThanEqual(String skuCode, Integer quantity);


}
